---
atomic_key: hospitalization_id

reference:
    table: clif_hospitalization
    start_dttm: admission_dttm
    end_dttm: discharge_dttm
    age: age_at_admission

augmentation_tables:
    - table: clif_patient
      key: patient_id
      validation: "m:1"

times_qc:
    table: clif_vitals
    dttm: recorded_dttm

prefix:
    - column: race_category
      prefix: RACE
    - column: ethnicity_category
      prefix: ETHN
    - column: sex_category
      prefix: SEX
    - column: quantized_age
    - column: admission_type_name
      prefix: ADMN

events:
    - table: clif_adt
      prefix: XFR
      category: location_category
      value: ~
      dttm: in_dttm

    - table: clif_labs
      prefix: LAB
      category: lab_category
      value: lab_value_numeric
      dttm: lab_result_dttm

    - table: clif_vitals
      prefix: VTL
      category: vital_category
      value: vital_value
      dttm: recorded_dttm

    - table: clif_medication_admin_continuous
      prefix: MED
      category: med_category
      value: med_dose
      dttm: admin_dttm

    # quantitative assessments
    - table: clif_patient_assessments
      prefix: ASMT
      filter: pl.col("numerical_value").is_not_null()
      category: assessment_category
      value: numerical_value
      dttm: recorded_dttm

    #qualitative assessments
    - table: clif_patient_assessments
      prefix: ASMT
      filter: pl.col("numerical_value").is_null()
      category:
          - assessment_category
          - categorical_value
      value: ~
      dttm: recorded_dttm

    - table: clif_respiratory_support
      prefix: RESP
      category:
          - mode_category
          - device_category
      value: ~
      dttm: recorded_dttm

    - table: clif_position
      prefix: POSN
      filter: pl.col("position_category") == "prone"
      category:
          - position_category
      value: ~
      dttm: recorded_dttm

suffix:
    - column: discharge_category
      prefix: DSCG
